- name: Ubuntu Upgrades Complete Process
  hosts: ~tag_Name_{{ hostname }}
  gather_facts: false
  tasks:
    - name: Gathering ec2 facts
      action: ec2_facts
    - name: Instance Register
      with_items: ec2_elbs
      local_action:
        module: ec2_elb
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{% if elb_list is defined %}{{ elb_list }}{% else %}{{ item }}{% endif %}"
        state: present
        region: "{{ ansible_ec2_placement_region }}"
        wait: no
