- name: Remove bprobe
  hosts: ~tag_Name_tech-mktg-www0-qa.2u.com:~tag_Name_sandbox-oars-www1-qa.2u.com:~tag_Name_sandbox-lms-cron-qa.2u.com:~tag_Name_sandbox-lms-api1-qa.2u.com:~tag_Name_sandbox-mdb1-qa.2u.com:~tag_Name_sandbox-oars-www0-qa.2u.com:~tag_Name_sandbox-lms-www1-qa.2u.com:~tag_Name_sandbox-mdb0-qa.2u.com:~tag_Name_sandbox-lms-www0-qa.2u.com:~tag_Name_sandbox-lms-www2-qa.2u.com:~tag_Name_tech-mktg-www2-qa.2u.com:~tag_Name_tech-mktg-www3-qa.2u.com:~tag_Name_sandbox-marb-qa.2u.com:~tag_Name_sandbox-lms-api0-qa.2u.com:~tag_Name_tech-mktg-www1-qa.2u.com
  gather_facts: yes
  sudo: yes
  tasks:
    - name: Run apt-get update
      command: sudo apt-get update
    - name: stop the bprobe process
      command: sudo /etc/init.d/bprobe stop
    - name: Apt-get remove bprobe
      apt: name=bprobe state=absent purge=yes
