- name: Remove from /etc/hosts
  hosts: ~tag_(E|e)nvironment_(stg|QA|Development|Staging|sb):~tag_Name_tech-jenkins-qa.2u.com:!~tag_Name_operations:!~tag_Name_tech-ops-jenkins-dev.2u.com
  # hosts: ~tag_Environment_test
  gather_facts: yes
  sudo: yes
  tasks:
    - name: remove 54.231.32.0 s3.amazonaws.com
      lineinfile: dest=/etc/hosts regexp="^54.231.32.0\s*s3.amazonaws.com" line="54.231.32.0 s3.amazonaws.com" backup=yes state=absent
    - name: remove 54.231.32.1 bucket.s3.amazonaws.com
      lineinfile: dest=/etc/hosts regexp="^54.231.32.1\s*bucket.s3.amazonaws.com" line="54.231.32.1 bucket.s3.amazonaws.com" state=absent
    - name: remove 54.231.32.3 bucket.s3-external-1.amazonaws.com
      lineinfile: dest=/etc/hosts regexp="^54.231.32.3\s*bucket.s3-external-1.amazonaws.com" line="54.231.32.3 bucket.s3-external-1.amazonaws.com" state=absent
    - name: check sslv3 connection s3.amazonaws.com
      command: curl -3 -IL https://s3.amazonaws.com/2tor-test/
      changed_when: False
    - name: check sslv3 connection bucket.s3.amazonaws.com
      command: curl -3 -IL https://bucket.s3.amazonaws.com/2tor-test/
      changed_when: False
    - name: check sslv3 connection bucket.s3-external-1.amazonaws.com
      command: curl -3 -IL https://bucket.s3-external-1.amazonaws.com/2tor-test/
      changed_when: False
